### PR TITLE
[Fix #11] Remove reflection warning

### LINKED ISSUE #11: Reflection warning
```
Reflection warning: file:/Users/erik/Documents/github.com/primitive-math/src/primitive_math.clj:266:3 - call to java.math.BigInteger ctor cannot be resolved
```

### PR DESCRIPTION
**Pull request by slipset**

### CODE REVIEW

**Comment by KingMob** [comment]
@slipset Hey Erik, how did you get the reflection warning? What versions of clojure/JDK are you on? I tried a few different combinations, but I couldn't replicate it.

I see a _different_ reflection warning when testing ("call to static method add on primitive_math.Primitives can't be resolved (argument types: long, double)"), but that comes from the IllegalArgumentException test in `primitive-math-test`, so it's expected.

**Comment by KingMob** [comment]
I just fired up a random REPL, and BigInteger was already imported.

**Comment by slipset** [comment]
So the reflection warning comes when running the repl via CIDER:
```
;; Connected to nREPL server - nrepl://localhost:53599
;; CIDER 1.3.0-snapshot (package: 20220222.1710), nREPL 0.9.0
;; Clojure 1.10.0, Java 17.0.1
...
;;  Startup: /opt/homebrew/bin/lein update-in :dependencies conj \[nrepl/nrepl\ \"0.9.0\"\] -- update-in :dependencies conj \[acyclic/squiggly-clojure\ \"0.1.9-SNAPSHOT\"\] -- update-in :dependencies conj \[refactor-nrepl/refactor-nrepl\ \"3.3.2\"\] -- update-in :plugins conj \[refactor-nrepl/refactor-nrepl\ \"3.3.2\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.28.3\"\] -- update-in :plugins conj \[mx.cider/enrich-classpath\ \"1.9.0\"\] -- update-in :middleware conj cider.enrich-classpath/middleware -- repl :headless :host localhost
Reflection warning: file:/Users/erik/Documents/github.com/primitive-math/src/primitive_math.clj:266:3 - call to java.math.BigInteger ctor cannot be resolved
user> 
```
Whereas when I run the repl from the common line with `lein repl`, there is no such warning (but a couple of others:
```
erik@keep primitive-math % lein repl
Reflection warning, nrepl/transport.clj:103:5 - call to method write can't be resolved (target class is unknown).
Reflection warning, nrepl/util/completion.clj:148:34 - call to method split can't be resolved (target class is unknown).
Reflection warning, nrepl/util/completion.clj:159:12 - call to method contains can't be resolved (target class is unknown).
Reflection warning, nrepl/util/completion.clj:173:5 - call to method startsWith can't be resolved (target class is unknown).
Reflection warning, nrepl/util/completion.clj:174:5 - call to method contains can't be resolved (target class is unknown).
Reflection warning, nrepl/util/completion.clj:175:5 - call to method contains can't be resolved (target class is unknown).
Reflection warning, nrepl/util/completion.clj:186:35 - call to method startsWith can't be resolved (target class is unknown).
Reflection warning, /private/var/folders/h3/710ddf5j5s940zbr3lcnv_xh0000gn/T/form-init1908792134246220536.clj:1:2372 - reference to field deleteOnExit can't be resolved.
nREPL server started on port 53697 on host 127.0.0.1 - nrepl://127.0.0.1:53697
REPL-y 0.5.1, nREPL 0.8.3
Clojure 1.10.0
OpenJDK 64-Bit Server VM 17.0.1+1
Reflection warning, /private/var/folders/h3/710ddf5j5s940zbr3lcnv_xh0000gn/T/form-init1908792134246220536.clj:1:1580 - reference to field ns can't be resolved.
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (require 'primitive-math)
nil
user=>
```

**Comment by slipset** [comment]
I guess the reason I am/was investigating this is that I thought I'd read in some issue somewhere that the reason we took on this lib was that there was a reflection warning. But I see from https://github.com/clj-commons/meta/issues/67 that I was mistaken. So, we might just close this and the corresponding issue.

**Comment by KingMob** [comment]
I'm willing to say it's a CIDER-specific problem if you are. I couldn't replicate it with `lein repl`, with `clj -r`, or in IntelliJ with nREPL.

That being said, if you want to update the `import` to be explicit, that's fine with me.

**Pull request closed without merging**
